### PR TITLE
Added possibility to deactivate automatic startup in BundleActivator

### PR DESCRIPTION
**Pull request by SourcePond**
- Introduced new system property bitronix.tm.osgi.disableActivator
- Added documentation
- Added test for Activator

### CODE REVIEW

**Comment by lorban** [comment]
This looks like a hack to me. What kind of problem are you facing that you want to manually initialize the transaction manager?

**Comment by SourcePond** [comment]
In our application we have a bundle which manages DataSources. This bundle uses the transaction manager. The main thing is to inject configuration data programmatically: the configuration properties are not located in a property file but managed by a system wide settings service. The settings are then injected into the Configuration object just before the transaction manager is started. This is not possible when the transaction manager is already started because the Configuration object cannot be changed anymore. Now, I'm not sure if there is a better/other solution to inject configuration properties programmatically before the activator starts the TM. Until now, we maintain a custom Bitronix bundle which does not specify an activator in its manifest.

**Comment by lorban** [comment]
I'm far from an OSGi expert, but wouldn't refactoring the activator to make use of `ConfigurationAdmin` the right solution?

Relying on a system property really looks dirty and should only be done as a last resort.

**Comment by SourcePond** [comment]
You're right, ConfigAdmin would be the best solution. I'll close this pull-request and implement this requirement with the ConfigAdmin.

**Pull request closed without merging**
