### PR TITLE
Resolution of the issue #104 XAFactories which implement java.util.Map (MQXAConnectionFactory) cannot be initialized properly

### PR DESCRIPTION
**Pull request by tomasjura**
one additional fix : do not print passwords into log

### CODE REVIEW

**Comment by lorban** [comment]
Sweet, I mistakenly force-pushed an old version onto the master (wrong script, wrong folder, fat fingers) instead of updating my local repo.

Could you please force-push back the previous master to where it was (rev 3446b43) to restore it back to a reasonable state? I've just invited you to the committers role for this purpose. Many thanks and sorry for that.

Regarding your change, my first opinion is that you made something quite substantial which looks to have a much broader scope than the original `Map` problem. I would very much prefer to stick to the very narrow original scope here, if you'd like to experiment more I would encourage you to do so in your own fork.

Thanks and sorry for the mess.

**Comment by tomasjura** [comment]
I rewrote just one function: PropertyUtils.setProperty. The orginal (and preserved) design of that function suffers with several corner cases (related to ClonedProps), which lead IMO to unsolvable problems. The cases are described in the comment of that function. I tried to handle them as best I could ( - code do not call setters when they don't exists ), but still the call of setters along the property path is a heuristics which may fail for some obscure cases. The solution of original Map problem just show those cases in full range and there was no other way than the complete rewrite of setProperty function.

**Comment by lorban** [comment]
Sorry for the long delay getting back to you. You haven't rebased your branch on top of the master, so this makes reviewing your PR rather complicated.

In any case, I would encourage you to make your changes in your own fork as I do not have the time anymore to maintain BTM, let alone review PRs in a timely manner.

Sorry & good luck with your customizations.

**Comment by tomasjura** [comment]
I hope I did it correctly.  At least on the github web page it seems to be merged. Now I fighting with the XA session init. Basically I'm writing the JMS consumer in the Tomcat. But the DualSessionWrapper do not returns the XASession, unless XA transaction is started, and do not supports createXASession (why? Shouldn't it implement XASession?).

**Pull request closed without merging**
